Update common package to fix bugs
fission/keda-connectors pull request #36
Opened 2020-10-14 10:28 UTC by harshthakur9030

Signed-off-by: Harsh Thakur <harshthakur9030@gmail.com>

Need to update the common package to fix some bugs related to sending POST request to endpoint and handling response returned.

2020-10-14 10:40 UTC, therahulbhati requested changes

2020-10-14 10:40 UTC, therahulbhati commented on common/go.sum
> +github.com/aws/aws-sdk-go v1.35.7 h1:FHMhVhyc/9jljgFAcGkQDYjpC9btM0B8VfkLBfctdNE=
Can we revert aws related code changes?

2020-10-14 10:51 UTC, therahulbhati approved these changes

2020-10-14 11:33 UTC, merged

2020-11-10 15:30 UTC, chetanpdeshmukh commented
Hello @harshthakur9030 ,
Thanks again for the PR!

Thank you for contributing to Fission project. Could you please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSdhxtWL5N2PU7MYC2IRRAzYw-CrG9QtsYNvkiiOPVEQj8i51w/viewform?usp=sf_link), so we can send you the well deserved awesome swags :)

Team Fission